# Generated by Django 6.0.4 on 2026-04-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_transaction_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Housing', 'Housing'), ('Healthcare', 'Healthcare'), ('Entertainment', 'Entertainment '), ('Other', 'Other')], max_length=20),
        ),
    ]
